const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Hosts allowed to use cleartext (ws://).
 *
 * Android's network security config matches host names and not CIDR ranges, so
 * every local address has to be listed explicitly. Keep in sync with
 * mobile/.env if the development machine's LAN address changes.
 */
const LOCAL_HOSTS = ['192.168.0.42', '10.0.2.2', 'localhost', '127.0.0.1'];

/**
 * Lets a preview/release build reach a Gun relay running on the developer's own
 * machine over ws://.
 *
 * The main manifest does not set usesCleartextTraffic, so Android blocks plain
 * WebSockets. That is what we want for a published app: a relay on the internet
 * must be wss://. Only these local hosts are exempted, everything else still
 * requires TLS, so a build uploaded to Google Play is not weakened by this.
 *
 * This has to be a config plugin rather than a file inside android/, because
 * android/ is git-ignored: EAS regenerates it with prebuild, so any file written
 * there directly would be lost before the build starts.
 */
const withLocalNetworkCleartext = (config) => {
  // 1. Declare the config in the manifest so Android picks it up.
  config = withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (application) {
      application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }
    return cfg;
  });

  // 2. Write the config itself, into the generated res/xml folder.
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      const file = path.join(dir, 'network_security_config.xml');

      const domains = LOCAL_HOSTS.map((h) => `        <domain includeSubdomains="false">${h}</domain>`).join('\n');

      const xml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withLocalNetworkCleartext.js - do not edit by hand. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
${domains}
    </domain-config>

    <base-config cleartextTrafficPermitted="false" />
</network-security-config>
`;

      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(file, xml);
      return cfg;
    },
  ]);

  return config;
};

module.exports = withLocalNetworkCleartext;
